version: "3.8"

services:
  terraria:
    image: "ryshe/terraria:vanilla-1.4.4.5"
    container_name: "terraria"
    tty: true
    stdin_open: true
    ports:
      - "7777:7777"
    environment:
      TZ: "Asia/Tokyo"
      WORLD_FILENAME: "Corrupt-world.wld"
    volumes:
      - "./terraria:/root/.local/share/Terraria/Worlds"
    restart: unless-stopped
